package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;
import javax.persistence.Id;




/**
 * Actie generated by hbm2java
 * Actie pojo klasse, houdt informatie bij over de lading en de opdracht.
 */
@Entity
public class Actie  implements java.io.Serializable {

    @Id
     private int actieid;
     private int transportid;
     private int opdrachtid;
     private Boolean actieklaar;
     private String lading;
     private String vrijveld;

    public Actie() {
    }

	
    public Actie(int actieid, int transportid, int opdrachtid) {
        this.actieid = actieid;
        this.transportid = transportid;
        this.opdrachtid = opdrachtid;
    }
    public Actie(int actieid, Transportadres transportadres, Opdracht opdracht, Boolean actieklaar, String lading, String vrijveld) {
       this.actieid = actieid;
       this.transportid = transportid;
       this.opdrachtid = opdrachtid;
       this.actieklaar = actieklaar;
       this.lading = lading;
       this.vrijveld = vrijveld;
    }
   
    public int getActieid() {
        return this.actieid;
    }
    
    public void setActieid(int actieid) {
        this.actieid = actieid;
    }
    public int getTransportid() {
        return this.transportid;
    }
    
    public void setTransportid(int transportid) {
        this.transportid = transportid;
    }
    public int getOpdrachtid() {
        return this.opdrachtid;
    }
    
    public void setOpdrachtid(int opdrachtid) {
        this.opdrachtid = opdrachtid;
    }
    public Boolean getActieklaar() {
        return this.actieklaar;
    }
    
    public void setActieklaar(Boolean actieklaar) {
        this.actieklaar = actieklaar;
    }
    public String getLading() {
        return this.lading;
    }
    
    public void setLading(String lading) {
        this.lading = lading;
    }
    public String getVrijveld() {
        return this.vrijveld;
    }
    
    public void setVrijveld(String vrijveld) {
        this.vrijveld = vrijveld;
    }




}


