package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Persoonsinfo generated by hbm2java
 * persoonelijke info van werknemers.
 */
public class Persoonsinfo  implements java.io.Serializable {


     private int infoid;
     private String rijksregisternr;
     private String siskaart;
     private String identiteitsnr;
     private String persioennr;
     private String geboorteplaats;
     private Date geboortedatum;
     private String iban;
     private String bic;
     private String burgerstand;
     private int aantalkinderen;

    public Persoonsinfo() {
    }

	
    public Persoonsinfo(int infoid, String rijksregisternr, String siskaart, String identiteitsnr, String persioennr, String geboorteplaats, Date geboortedatum, String iban, String bic) {
        this.infoid = infoid;
        this.rijksregisternr = rijksregisternr;
        this.siskaart = siskaart;
        this.identiteitsnr = identiteitsnr;
        this.persioennr = persioennr;
        this.geboorteplaats = geboorteplaats;
        this.geboortedatum = geboortedatum;
        this.iban = iban;
        this.bic = bic;
    }
    public Persoonsinfo(int infoid, String rijksregisternr, String siskaart, String identiteitsnr, String persioennr, String geboorteplaats, Date geboortedatum, String iban, String bic, String burgerstand, int aantalkinderen) {
       this.infoid = infoid;
       this.rijksregisternr = rijksregisternr;
       this.siskaart = siskaart;
       this.identiteitsnr = identiteitsnr;
       this.persioennr = persioennr;
       this.geboorteplaats = geboorteplaats;
       this.geboortedatum = geboortedatum;
       this.iban = iban;
       this.bic = bic;
       this.burgerstand = burgerstand;
       this.aantalkinderen = aantalkinderen;
    }
   
    public int getInfoid() {
        return this.infoid;
    }
    
    public void setInfoid(int infoid) {
        this.infoid = infoid;
    }
    public String getRijksregisternr() {
        return this.rijksregisternr;
    }
    
    public void setRijksregisternr(String rijksregisternr) {
        this.rijksregisternr = rijksregisternr;
    }
    public String getSiskaart() {
        return this.siskaart;
    }
    
    public void setSiskaart(String siskaart) {
        this.siskaart = siskaart;
    }
    public String getIdentiteitsnr() {
        return this.identiteitsnr;
    }
    
    public void setIdentiteitsnr(String identiteitsnr) {
        this.identiteitsnr = identiteitsnr;
    }
    public String getPersioennr() {
        return this.persioennr;
    }
    
    public void setPersioennr(String persioennr) {
        this.persioennr = persioennr;
    }
    public String getGeboorteplaats() {
        return this.geboorteplaats;
    }
    
    public void setGeboorteplaats(String geboorteplaats) {
        this.geboorteplaats = geboorteplaats;
    }
    public Date getGeboortedatum() {
        return this.geboortedatum;
    }
    
    public void setGeboortedatum(Date geboortedatum) {
        this.geboortedatum = geboortedatum;
    }
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }
    public String getBic() {
        return this.bic;
    }
    
    public void setBic(String bic) {
        this.bic = bic;
    }
    public String getBurgerstand() {
        return this.burgerstand;
    }
    
    public void setBurgerstand(String burgerstand) {
        this.burgerstand = burgerstand;
    }
    public int getAantalkinderen() {
        return this.aantalkinderen;
    }
    
    public void setAantalkinderen(int aantalkinderen) {
        this.aantalkinderen = aantalkinderen;
    }




}


