package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA

/**
 * Postcode generated by hbm2java
 * Postcode informatie.
 */
public class Postcode  implements java.io.Serializable {

     private String postcode;
     private String gemeente;

    public Postcode() {
    }
    
    public Postcode(String postcode, String gemeente) {
        this.postcode = postcode;
        this.gemeente = gemeente;
    }
   
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public String getGemeente() {
        return this.gemeente;
    }
    
    public void setGemeente(String gemeente) {
        this.gemeente = gemeente;
    }
}