package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Rijbewijsgegevens generated by hbm2java
 * Rijbewijs gegevens.
 */
public class Rijbewijsgegevens  implements java.io.Serializable {


     private int rijbewijsid;
     private String rijbewijsnr;
     private String rijbewijscat;
     private Date geldigtot;
     private Boolean adrcertificaat;
     private Boolean medischattest;
     private String tankkaartnr;
     private String tachograafnr;
     private int tachograaftot;

    public Rijbewijsgegevens() {
    }

	
    public Rijbewijsgegevens(int rijbewijsid, String rijbewijsnr, String rijbewijscat, Date geldigtot, String tankkaartnr, String tachograafnr) {
        this.rijbewijsid = rijbewijsid;
        this.rijbewijsnr = rijbewijsnr;
        this.rijbewijscat = rijbewijscat;
        this.geldigtot = geldigtot;
        this.tankkaartnr = tankkaartnr;
        this.tachograafnr = tachograafnr;
    }
    public Rijbewijsgegevens(int rijbewijsid, String rijbewijsnr, String rijbewijscat, Date geldigtot, Boolean adrcertificaat, Boolean medischattest, String tankkaartnr, String tachograafnr, int tachograaftot) {
       this.rijbewijsid = rijbewijsid;
       this.rijbewijsnr = rijbewijsnr;
       this.rijbewijscat = rijbewijscat;
       this.geldigtot = geldigtot;
       this.adrcertificaat = adrcertificaat;
       this.medischattest = medischattest;
       this.tankkaartnr = tankkaartnr;
       this.tachograafnr = tachograafnr;
       this.tachograaftot = tachograaftot;
    }
   
    public int getRijbewijsid() {
        return this.rijbewijsid;
    }
    
    public void setRijbewijsid(int rijbewijsid) {
        this.rijbewijsid = rijbewijsid;
    }
    public String getRijbewijsnr() {
        return this.rijbewijsnr;
    }
    
    public void setRijbewijsnr(String rijbewijsnr) {
        this.rijbewijsnr = rijbewijsnr;
    }
    public String getRijbewijscat() {
        return this.rijbewijscat;
    }
    
    public void setRijbewijscat(String rijbewijscat) {
        this.rijbewijscat = rijbewijscat;
    }
    public Date getGeldigtot() {
        return this.geldigtot;
    }
    
    public void setGeldigtot(Date geldigtot) {
        this.geldigtot = geldigtot;
    }
    public Boolean getAdrcertificaat() {
        return this.adrcertificaat;
    }
    
    public void setAdrcertificaat(Boolean adrcertificaat) {
        this.adrcertificaat = adrcertificaat;
    }
    public Boolean getMedischattest() {
        return this.medischattest;
    }
    
    public void setMedischattest(Boolean medischattest) {
        this.medischattest = medischattest;
    }
    public String getTankkaartnr() {
        return this.tankkaartnr;
    }
    
    public void setTankkaartnr(String tankkaartnr) {
        this.tankkaartnr = tankkaartnr;
    }
    public String getTachograafnr() {
        return this.tachograafnr;
    }
    
    public void setTachograafnr(String tachograafnr) {
        this.tachograafnr = tachograafnr;
    }
    public int getTachograaftot() {
        return this.tachograaftot;
    }
    
    public void setTachograaftot(int tachograaftot) {
        this.tachograaftot = tachograaftot;
    }




}


