package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Voertuig generated by hbm2java
 * Informatie over voertuigen.
 */
public class Voertuig  implements java.io.Serializable {


     private int voertuigid;
     private int opleggerid;
     private String nummerplaat;
     private Boolean actief;
     private String omschrijving;
     private String voertuigtype;
     private String bouwjaar;
     private Date datumin;
     private Date datumuit;
     private String chassisnummer;
     private String motornummer;
     private Boolean vergunning;
     private Date vergunninggeldigtot;
     private String vrijveld;

    public Voertuig() {
    }

	
    public Voertuig(int voertuigid) {
        this.voertuigid = voertuigid;
    }
    public Voertuig(int voertuigid, int opleggerid, String nummerplaat, Boolean actief, String omschrijving, String voertuigtype, String bouwjaar, Date datumin, Date datumuit, String chassisnummer, String motornummer, Boolean vergunning, Date vergunninggeldigtot, String vrijveld) {
       this.voertuigid = voertuigid;
       this.opleggerid = opleggerid;
       this.nummerplaat = nummerplaat;
       this.actief = actief;
       this.omschrijving = omschrijving;
       this.voertuigtype = voertuigtype;
       this.bouwjaar = bouwjaar;
       this.datumin = datumin;
       this.datumuit = datumuit;
       this.chassisnummer = chassisnummer;
       this.motornummer = motornummer;
       this.vergunning = vergunning;
       this.vergunninggeldigtot = vergunninggeldigtot;
       this.vrijveld = vrijveld;
    }
   
    public int getVoertuigid() {
        return this.voertuigid;
    }
    
    public void setVoertuigid(int voertuigid) {
        this.voertuigid = voertuigid;
    }
    
    public int getOpleggerid() {
        return this.opleggerid;
    }
    
    public void setOpleggerid(int opleggerid) {
        this.opleggerid = opleggerid;
    }
    
    public String getNummerplaat() {
        return this.nummerplaat;
    }
    
    public void setNummerplaat(String nummerplaat) {
        this.nummerplaat = nummerplaat;
    }
    
    public Boolean getActief() {
        return this.actief;
    }
    
    public void setActief(Boolean actief) {
        this.actief = actief;
    }
    
    public String getOmschrijving() {
        return this.omschrijving;
    }
    
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }
    
    public String getVoertuigtype() {
        return this.voertuigtype;
    }
    
    public void setVoertuigtype(String voertuigtype) {
        this.voertuigtype = voertuigtype;
    }
    
    public String getBouwjaar() {
        return this.bouwjaar;
    }
    
    public void setBouwjaar(String bouwjaar) {
        this.bouwjaar = bouwjaar;
    }
    
    public Date getDatumin() {
        return this.datumin;
    }
    
    public void setDatumin(Date datumin) {
        this.datumin = datumin;
    }
    
    public Date getDatumuit() {
        return this.datumuit;
    }
    
    public void setDatumuit(Date datumuit) {
        this.datumuit = datumuit;
    }
    
    public String getChassisnummer() {
        return this.chassisnummer;
    }
    
    public void setChassisnummer(String chassisnummer) {
        this.chassisnummer = chassisnummer;
    }
    
    public String getMotornummer() {
        return this.motornummer;
    }
    
    public void setMotornummer(String motornummer) {
        this.motornummer = motornummer;
    }
    public Boolean getVergunning() {
        return this.vergunning;
    }
    
    public void setVergunning(Boolean vergunning) {
        this.vergunning = vergunning;
    }
    public Date getVergunninggeldigtot() {
        return this.vergunninggeldigtot;
    }
    
    public void setVergunninggeldigtot(Date vergunninggeldigtot) {
        this.vergunninggeldigtot = vergunninggeldigtot;
    }
    public String getVrijveld() {
        return this.vrijveld;
    }
    
    public void setVrijveld(String vrijveld) {
        this.vrijveld = vrijveld;
    }
}


